GET http://localhost:5000/books
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGVuIiwiaWF0IjoxNjY3MTg5ODMzLCJleHAiOjE2NjcxODk4NjN9.uFBy3OtTIz-TcS-wMAnDOSbh5v3xo1hmTR-Y-SQGSqU

###

POST http://localhost:5500/login
Content-Type: application/json

{
    "username": "Helen"
}